@startuml

left to right direction
skinparam packageStyle rect

title Diagrama Casos de uso AnyDay

actor UsuariNoRegistrat as usuariNoRegistrat
actor UsuariRegistrat as usuariRegistrat

rectangle AnyDay {

usecase (UC1. Registrarse)  as UC1
usecase (UC2. Iniciar Sesión) as UC2
usecase (UC3. Entrar al perfil) as UC3
usecase (UC3.1 Editar perfil) as UC31
usecase (UC4. Calendario) as UC4
usecase (UC4.1 Visualizar eventos) as UC41
usecase (UC4.2 Selccionar dia) as UC42
usecase (UC4.3 Cambiar mes) as UC43
usecase (UC4.5 Configuración) as UC45
usecase (UC5. Social) as UC5
usecase (UC5.1 Configuración) as UC51
usecase (UC5.1.1 Solicitudes) as UC511
usecase (UC5.2 Grupos) as UC52
usecase (UC5.2.1 Crear grupo) as UC521
usecase (UC5.3 Amigos) as UC53
usecase (UC5.3.1 Añadir amigo) as UC531
usecase (UC6. Eventos destacados) as UC6
usecase (UC6.1 Apuntarse a evento) as UC61
usecase (UC6.2 Buscar eventos publicos) as UC62
usecase (UC7. Crear evento) as UC7
usecase (UC8. Configuración) as UC8
usecase (UC8.1 Gestión aplicacion) as UC81

usuariNoRegistrat -- UC1
usuariRegistrat -- UC2
usuariRegistrat -- UC3
usuariRegistrat -- UC4
usuariRegistrat -- UC5
usuariRegistrat -- UC6
usuariRegistrat -- UC7
usuariRegistrat -- UC8


UC4 ---|> UC41
UC4 ---|> UC42
UC4 ---|> UC43
UC4 ---|> UC45
UC511 ---|> UC51
UC521 ---|> UC52
UC531 ---|> UC53
UC61 ---|> UC6
UC61 ---|> UC4

UC5 ...> UC51 : <<include>>
UC5 ...> UC52 : <<include>>
UC5 ...> UC53 : <<include>>
UC6 ...> UC62 : <<include>>
UC8 ...> UC81 : <<include>>
UC2 ...> UC1 : <<include>>
UC3 ...> UC31 : <<include>>
UC4 ...> UC7 : <<include>>

UC45 ...> UC8 : <<extends>>
UC51 ...> UC8 : <<extends>>




}

@enduml